service: example-service

frameworkVersion: '>=2.72.2 <3.0.0'

provider:
  name: aws
  runtime: go1.x # or provided.al2
  architecture: x86_64 # or arm64
  region: eu-central-1

plugins:
  - serverless-golang

functions:
  example:
    handler: ./functions/example/main.go # or just "./functions/example"
